#!/usr/bin/env node
/**
 * Emits orca's OpenAPI spec to ui/openapi.json — the committed, deterministic
 * input for `openapi-ts`.
 *
 * Why a committed file instead of codegen straight off a live daemon: pointing
 * the generator at http://localhost:12000 meant the client could only be
 * regenerated by whoever happened to have a dev daemon up, nothing in CI could
 * verify it, and the client silently rotted ~3 months behind the API (it still
 * exported `pod.*`/`vm.*`/`lxc.*` verbs that no longer exist). A committed spec
 * makes every API change a reviewable diff and lets CI gate client staleness
 * without needing an orca binary.
 *
 * `orca openapi emit` is byte-identical to GET /api/openapi.json but needs no
 * server boot. Keys are sorted and re-indented here so an unrelated change in
 * orca's serialization order can't produce a phantom diff.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const ORCA = process.env.ORCA_BIN ?? 'orca';

let raw;
try {
  raw = execFileSync(ORCA, ['openapi', 'emit'], {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    // jemalloc chatters on stderr; let it through to the terminal, not stdout.
    stdio: ['ignore', 'pipe', 'inherit'],
  });
} catch (err) {
  console.error(
    `\n  Could not run \`${ORCA} openapi emit\`.\n` +
      `  Install orca, or set ORCA_BIN to its path.\n` +
      `  (Spec emission needs the orca binary; regenerating the client from the\n` +
      `   already-committed ui/openapi.json does not — use \`npm run gen:client\`.)\n`
  );
  throw err;
}

const spec = JSON.parse(raw);
writeFileSync('openapi.json', JSON.stringify(spec, sortedReplacer, 2) + '\n');

const paths = Object.keys(spec.paths ?? {}).length;
const schemas = Object.keys(spec.components?.schemas ?? {}).length;
console.log(`openapi.json  ${spec.info?.version ?? '?'}  ${paths} paths, ${schemas} schemas`);

/** Stable key order so the committed file diffs only on real API changes. */
function sortedReplacer(_key, value) {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) return value;
  return Object.fromEntries(Object.keys(value).sort().map((k) => [k, value[k]]));
}
